// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxmMJPJsi_p6v6ffQThFuh3xJhT_EvAI',
    appId: '1:667318368464:web:57f65d121ec29a81db06d5',
    messagingSenderId: '667318368464',
    projectId: 'pasada-9d699',
    authDomain: 'pasada-9d699.firebaseapp.com',
    storageBucket: 'pasada-9d699.firebasestorage.app',
    measurementId: 'G-3WH94C7NK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjgzc70vdhB1wEwAEU8riL8QuMYQ_uQLk',
    appId: '1:667318368464:android:a4a1fc3e617ac637db06d5',
    messagingSenderId: '667318368464',
    projectId: 'pasada-9d699',
    storageBucket: 'pasada-9d699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_pyXM9LuuthDlrbe0YcVqMZ3rzjc3nfY',
    appId: '1:667318368464:ios:8157d195c7d99ce6db06d5',
    messagingSenderId: '667318368464',
    projectId: 'pasada-9d699',
    storageBucket: 'pasada-9d699.firebasestorage.app',
    iosBundleId: 'com.example.pasadaPassengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_pyXM9LuuthDlrbe0YcVqMZ3rzjc3nfY',
    appId: '1:667318368464:ios:8157d195c7d99ce6db06d5',
    messagingSenderId: '667318368464',
    projectId: 'pasada-9d699',
    storageBucket: 'pasada-9d699.firebasestorage.app',
    iosBundleId: 'com.example.pasadaPassengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKxmMJPJsi_p6v6ffQThFuh3xJhT_EvAI',
    appId: '1:667318368464:web:8420c25f9a5e861fdb06d5',
    messagingSenderId: '667318368464',
    projectId: 'pasada-9d699',
    authDomain: 'pasada-9d699.firebaseapp.com',
    storageBucket: 'pasada-9d699.firebasestorage.app',
    measurementId: 'G-9GW10KCHDW',
  );
}
