// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// ignore_for_file: directives_ordering
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['WINDOWS_WEB_FIREBASE_KEY'] ?? '',
        appId: '1:667318368464:web:57f65d121ec29a81db06d5',
        messagingSenderId: '667318368464',
        projectId: 'pasada-9d699',
        authDomain: 'pasada-9d699.firebaseapp.com',
        storageBucket: 'pasada-9d699.firebasestorage.app',
        measurementId: 'G-3WH94C7NK3',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['ANDROID_FIREBASE_KEY'] ?? '',
        appId: '1:667318368464:android:a4a1fc3e617ac637db06d5',
        messagingSenderId: '667318368464',
        projectId: 'pasada-9d699',
        storageBucket: 'pasada-9d699.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['IOS_MACOS_FIREBASE_KEY'] ?? '',
        appId: '1:667318368464:ios:8157d195c7d99ce6db06d5',
        messagingSenderId: '667318368464',
        projectId: 'pasada-9d699',
        storageBucket: 'pasada-9d699.firebasestorage.app',
        iosBundleId: 'com.example.pasadaPassengerApp',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['IOS_MACOS_FIREBASE_KEY'] ?? '',
        appId: '1:667318368464:ios:8157d195c7d99ce6db06d5',
        messagingSenderId: '667318368464',
        projectId: 'pasada-9d699',
        storageBucket: 'pasada-9d699.firebasestorage.app',
        iosBundleId: 'com.example.pasadaPassengerApp',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['WINDOWS_WEB_FIREBASE_KEY'] ?? '',
        appId: '1:667318368464:web:8420c25f9a5e861fdb06d5',
        messagingSenderId: '667318368464',
        projectId: 'pasada-9d699',
        authDomain: 'pasada-9d699.firebaseapp.com',
        storageBucket: 'pasada-9d699.firebasestorage.app',
        measurementId: 'G-9GW10KCHDW',
      );
}
